name: check2gether
description: "The new shared list app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  google_fonts: ^6.2.1

  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1

  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

#assets:
  #- assets/
  #- assets/icons/
