name: list_repository
description: The Repo that handles lists
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
    
  equatable: ^2.0.5
  firebase_auth: ^5.2.1
  cloud_firestore: ^5.4.1
  firebase_storage: ^12.3.0
  rxdart: ^0.28.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true